# Generated by Django 5.2.8 on 2025-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0002_student_email_student_name_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
