# Generated by Django 5.2.7 on 2025-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0005_remove_student_enrollment_date_enrollment_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitted_homework',
            name='grade',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True),
        ),
    ]
