# Generated by Django 5.2.7 on 2025-11-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0006_alter_submitted_homework_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submitted_Homework',
            new_name='SubmittedHomework',
        ),
    ]
