# Generated by Django 5.2.7 on 2025-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0007_rename_submitted_homework_submittedhomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
