# Generated by Django 5.2.7 on 2025-12-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0009_student_user_teacher_user_alter_enrollment_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
    ]
