# Generated by Django 5.2.7 on 2025-12-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0010_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
