# Generated by Django 5.2.8 on 2025-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0011_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedhomework',
            name='submitted_file',
        ),
        migrations.AddField(
            model_name='submittedhomework',
            name='submitted_text',
            field=models.TextField(default='my homework text'),
        ),
    ]
