# Generated by Django 5.2.8 on 2025-12-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_managing', '0012_remove_submittedhomework_submitted_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedhomework',
            name='submitted_text',
            field=models.TextField(),
        ),
    ]
